// Code generated by redaction/scripts/generate.mjs from redaction/patterns.json. DO NOT EDIT.

/** One generated secret pattern. `source` and `flags` feed the RegExp constructor. */
export interface GeneratedPattern {
  id: string;
  source: string;
  flags: string;
}

/** A tier 2 pattern also carries the replacement template that keeps the key. */
export interface GeneratedTier2Pattern extends GeneratedPattern {
  replacement: string;
}

// High-confidence secret formats, applied by both redaction modes. No pattern
// contains a capturing group: redaction.ts alternates them into a single regex
// and maps the match group index back to a pattern id.
export const tier1Patterns: readonly GeneratedPattern[] = [
  { id: 'grafana-cloud-token', source: '\\bglc_[A-Za-z0-9_-]{20,}', flags: 'g' },
  { id: 'grafana-service-account-token', source: '\\bglsa_[A-Za-z0-9_-]{20,}', flags: 'g' },
  { id: 'aws-access-token', source: '\\b(?:A3T[A-Z0-9]|AKIA|ASIA|ABIA|ACCA)[A-Z2-7]{16}\\b', flags: 'g' },
  { id: 'github-pat', source: '\\bghp_[A-Za-z0-9_]{36,}', flags: 'g' },
  { id: 'github-oauth', source: '\\bgho_[A-Za-z0-9_]{36,}', flags: 'g' },
  { id: 'github-app-token', source: '\\bghs_[A-Za-z0-9_]{36,}', flags: 'g' },
  { id: 'github-fine-grained-pat', source: '\\bgithub_pat_[A-Za-z0-9_]{82}', flags: 'g' },
  { id: 'anthropic-api-key', source: '\\bsk-ant-api03-[a-zA-Z0-9_-]{93}AA', flags: 'g' },
  { id: 'anthropic-admin-key', source: '\\bsk-ant-admin01-[a-zA-Z0-9_-]{93}AA', flags: 'g' },
  { id: 'openai-api-key', source: '\\bsk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20}', flags: 'g' },
  { id: 'openai-project-key', source: '\\bsk-proj-[a-zA-Z0-9_-]{40,}', flags: 'g' },
  { id: 'openai-svcacct-key', source: '\\bsk-svcacct-[a-zA-Z0-9_-]{40,}', flags: 'g' },
  { id: 'gcp-api-key', source: '\\bAIza[A-Za-z0-9_-]{35}', flags: 'g' },
  {
    id: 'private-key',
    source: '-----BEGIN[A-Z ]*PRIVATE KEY-----[\\s\\S]*?-----END[A-Z ]*PRIVATE KEY-----',
    flags: 'g',
  },
  {
    id: 'connection-string',
    source: '(?:postgres|mysql|mongodb|redis|amqp)://[^ \\t\\n\\f\\r\\xa0\'"]+@[^ \\t\\n\\f\\r\\xa0\'"]+',
    flags: 'g',
  },
  { id: 'bearer-token', source: '[Bb]earer[ \\t\\n\\f\\r\\xa0]+[A-Za-z0-9_.\\-~+/]{20,}={0,3}', flags: 'g' },
  { id: 'slack-token', source: '\\bxox[bporas]-[A-Za-z0-9-]{10,}', flags: 'g' },
  { id: 'stripe-key', source: '\\b[sr]k_(?:live|test)_[A-Za-z0-9]{20,}', flags: 'g' },
  { id: 'sendgrid-api-key', source: '\\bSG\\.[A-Za-z0-9_-]{22}\\.[A-Za-z0-9_-]{43}', flags: 'g' },
  { id: 'twilio-api-key', source: '\\bSK[a-f0-9]{32}', flags: 'g' },
  { id: 'npm-token', source: '\\bnpm_[A-Za-z0-9]{36}', flags: 'g' },
  { id: 'pypi-token', source: '\\bpypi-[A-Za-z0-9_-]{50,}', flags: 'g' },
];

// Applied by both redaction modes when the caller enables email redaction.
export const emailPattern: GeneratedPattern = {
  id: 'email',
  source: '\\b[A-Za-z0-9._%+\\-]+@[A-Za-z0-9.\\-]+\\.[A-Za-z]{2,}\\b',
  flags: 'g',
};

// Heuristic key/value patterns, applied by full redaction only.
export const tier2Patterns: readonly GeneratedTier2Pattern[] = [
  {
    id: 'json-secret-field',
    source:
      '("(?:password|secret|token|credential|api_?key|private_?key|access_?key|client_?secret|auth_?token|secret_?key)"[ \\t\\n\\f\\r\\xa0]*:[ \\t\\n\\f\\r\\xa0]*")([^"]+)(")',
    flags: 'gi',
    replacement: '$1[REDACTED:json-secret-field]$3',
  },
  {
    id: 'env-secret-quoted-value',
    source:
      '(^|[^A-Za-z0-9])((?:PASSWORD|SECRET|TOKEN|KEY|CREDENTIAL|API_KEY|PRIVATE_KEY|ACCESS_KEY)[ \\t\\n\\f\\r\\xa0]*[=:][ \\t\\n\\f\\r\\xa0]*")([^"]+)(")',
    flags: 'gi',
    replacement: '$1$2[REDACTED:env-secret-quoted-value]$4',
  },
  {
    id: 'env-secret-value',
    source:
      '(^|[^A-Za-z0-9])((?:PASSWORD|SECRET|TOKEN|KEY|CREDENTIAL|API_KEY|PRIVATE_KEY|ACCESS_KEY)[ \\t\\n\\f\\r\\xa0]*[=:][ \\t\\n\\f\\r\\xa0]*)([^ \\t\\n\\f\\r\\xa0"{}\\[\\],]+)',
    flags: 'gi',
    replacement: '$1$2[REDACTED:env-secret-value]',
  },
];
