#!/usr/bin/env node
/**
 * Generates the per-language secret-pattern tables from redaction/patterns.json.
 *
 * Usage:
 *   node redaction/scripts/generate.mjs [outRoot] [--patterns <file>] [--no-format]
 *
 * outRoot defaults to the repository root. Passing a temporary directory is how
 * `mise run check:redaction` detects drift: it regenerates into the temp tree
 * and diffs against the committed files.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
export const repoRoot = path.resolve(scriptDir, '..', '..');
export const defaultPatternsFile = path.join(repoRoot, 'redaction', 'patterns.json');

const GENERATED_BY = 'redaction/scripts/generate.mjs';
const SOURCE_FILE = 'redaction/patterns.json';
const GO_HEADER = `// Code generated by ${GENERATED_BY} from ${SOURCE_FILE}. DO NOT EDIT.`;

// --- validation -------------------------------------------------------------

const ID_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const ALLOWED_FLAGS = new Set(['i']);
const TABLE_VERSION = 1;

// `\s`, `\w` and `\d` mean ASCII in Go RE2 and JavaScript and Unicode in Python
// and .NET, so a pattern using one matches different text in different engines.
// Patterns spell the class out instead. `[\s\S]` is exempt: a class and its
// complement mean "any character" in every engine.
const SHORTHAND_CLASS = /[sSwWdD]/;
const ANY_CHARACTER = '[\\s\\S]';

class PatternError extends Error {}

/**
 * Counts capturing groups and rejects constructs that are not portable across
 * the five engines. Character classes are tracked so `[(]` and `[\\]]` do not
 * confuse the scan.
 *
 * Returns the number of capturing groups and whether any of them is nested
 * inside another one.
 */
function scanRegex(id, source) {
  let groups = 0;
  let nested = false;
  let captureDepth = 0;
  const openGroups = [];
  let inClass = false;

  for (let i = 0; i < source.length; i++) {
    if (source.startsWith(ANY_CHARACTER, i)) {
      i += ANY_CHARACTER.length - 1;
      continue;
    }

    const ch = source[i];

    if (ch === '\\') {
      const next = source[i + 1];
      if (next === undefined) {
        throw new PatternError(`${id}: regex ends with a trailing backslash`);
      }
      if (!inClass && next >= '1' && next <= '9') {
        throw new PatternError(`${id}: backreference \\${next} is not supported by RE2`);
      }
      if (SHORTHAND_CLASS.test(next)) {
        throw new PatternError(
          `${id}: \\${next} means ASCII in Go and JavaScript and Unicode in Python and .NET; write the character class out`,
        );
      }
      i++;
      continue;
    }

    if (inClass) {
      if (ch === ']') inClass = false;
      continue;
    }

    if (ch === '[') {
      inClass = true;
      continue;
    }

    if (ch === ')') {
      if (openGroups.pop() === true) captureDepth--;
      continue;
    }

    if (ch !== '(') continue;

    if (source[i + 1] !== '?') {
      groups++;
      if (captureDepth > 0) nested = true;
      captureDepth++;
      openGroups.push(true);
      continue;
    }

    openGroups.push(false);
    const marker = source.slice(i + 1, i + 3);
    if (marker === '?<' || marker === "?'") {
      // `(?<name>` is a named group and `(?<=` / `(?<!` are lookbehind. Neither
      // is portable: Go RE2 rejects lookbehind and spells named groups `(?P<`.
      throw new PatternError(`${id}: lookbehind or named group "(${marker}" is not supported by RE2`);
    }
    if (marker === '?=' || marker === '?!') {
      throw new PatternError(`${id}: lookahead "(${marker}" is not supported by RE2`);
    }
  }

  if (inClass) {
    throw new PatternError(`${id}: regex has an unterminated character class`);
  }

  return { groups, nested };
}

/** Splits keepGroups into the preserved prefix, the replaced run, and the preserved suffix. */
function planReplacement(id, groupCount, keepGroups) {
  if (!Array.isArray(keepGroups) || keepGroups.length === 0) {
    throw new PatternError(`${id}: tier 2 patterns need a non-empty keepGroups array`);
  }
  for (let i = 0; i < keepGroups.length; i++) {
    const group = keepGroups[i];
    if (!Number.isInteger(group) || group < 1 || group > groupCount) {
      throw new PatternError(`${id}: keepGroups entry ${group} is not a capturing group (regex has ${groupCount})`);
    }
    if (i > 0 && group <= keepGroups[i - 1]) {
      throw new PatternError(`${id}: keepGroups must be strictly increasing`);
    }
  }

  const kept = new Set(keepGroups);
  const dropped = [];
  for (let group = 1; group <= groupCount; group++) {
    if (!kept.has(group)) dropped.push(group);
  }
  if (dropped.length === 0) {
    throw new PatternError(`${id}: keepGroups keeps every group, so nothing would be redacted`);
  }
  for (let i = 1; i < dropped.length; i++) {
    if (dropped[i] !== dropped[i - 1] + 1) {
      throw new PatternError(`${id}: groups left out of keepGroups must be contiguous, got ${dropped.join(', ')}`);
    }
  }

  return {
    before: keepGroups.filter((group) => group < dropped[0]),
    after: keepGroups.filter((group) => group > dropped[dropped.length - 1]),
  };
}

/** Validates the whole table and returns it enriched with derived fields. */
export function validateTable(table) {
  if (table === null || typeof table !== 'object' || !Array.isArray(table.patterns)) {
    throw new PatternError('patterns.json must be an object with a patterns array');
  }
  if (table.version !== TABLE_VERSION) {
    throw new PatternError(`patterns.json version must be ${TABLE_VERSION}, got ${JSON.stringify(table.version)}`);
  }
  if (table.patterns.length === 0) {
    throw new PatternError('patterns.json must declare at least one pattern');
  }

  const seen = new Set();
  const validated = table.patterns.map((pattern) => {
    const id = pattern.id;
    if (typeof id !== 'string' || !ID_PATTERN.test(id)) {
      throw new PatternError(`invalid pattern id ${JSON.stringify(id)}: expected kebab-case`);
    }
    if (seen.has(id)) {
      throw new PatternError(`${id}: duplicate pattern id`);
    }
    seen.add(id);

    if (pattern.tier !== 1 && pattern.tier !== 2 && pattern.tier !== 'email') {
      throw new PatternError(`${id}: tier must be 1, 2, or "email"`);
    }
    if (typeof pattern.regex !== 'string' || pattern.regex === '') {
      throw new PatternError(`${id}: regex must be a non-empty string`);
    }
    if (pattern.regex.includes('`')) {
      throw new PatternError(`${id}: regex must not contain a backtick (Go emits raw string literals)`);
    }
    if (/[\r\n]/.test(pattern.regex)) {
      throw new PatternError(`${id}: regex must not contain a line break`);
    }

    const flags = pattern.flags ?? [];
    if (!Array.isArray(flags)) {
      throw new PatternError(`${id}: flags must be an array`);
    }
    for (const flag of flags) {
      if (!ALLOWED_FLAGS.has(flag)) {
        throw new PatternError(`${id}: unsupported flag ${JSON.stringify(flag)}`);
      }
    }

    const { groups: groupCount, nested } = scanRegex(id, pattern.regex);
    try {
      new RegExp(pattern.regex, flags.join(''));
    } catch (err) {
      throw new PatternError(`${id}: regex does not compile: ${err.message}`);
    }

    if (pattern.tier === 1 || pattern.tier === 'email') {
      if (groupCount !== 0) {
        // Every engine alternates the tier 1 patterns into one regex and maps
        // the match group index back to a pattern id. An extra group shifts
        // that mapping and silently drops a later match from the output.
        throw new PatternError(
          `${id}: tier ${pattern.tier} patterns must not contain capturing groups, found ${groupCount}`,
        );
      }
      if (pattern.keepGroups !== undefined) {
        throw new PatternError(`${id}: keepGroups is only valid for tier 2 patterns`);
      }
      if (pattern.tier === 1 && flags.length > 0) {
        // The tier 1 patterns are alternated into one regex that is compiled
        // without flags, so a flag here reaches some engines and not others.
        // The email and tier 2 patterns are compiled on their own and do honor
        // their flags.
        throw new PatternError(`${id}: tier 1 patterns must not set flags, got ${JSON.stringify(flags)}`);
      }
      return { id, tier: pattern.tier, regex: pattern.regex, flags, groupCount };
    }

    if (nested) {
      // planReplacement treats the capturing groups as a left-to-right
      // partition. A group wrapping the redacted one would reprint the secret
      // next to the marker.
      throw new PatternError(`${id}: tier 2 patterns must not nest one capturing group inside another`);
    }

    const plan = planReplacement(id, groupCount, pattern.keepGroups);
    return { id, tier: 2, regex: pattern.regex, flags, groupCount, plan };
  });

  const tier1 = validated.filter((pattern) => pattern.tier === 1);
  const email = validated.filter((pattern) => pattern.tier === 'email');
  const tier2 = validated.filter((pattern) => pattern.tier === 2);

  if (tier1.length === 0) {
    throw new PatternError('patterns.json must declare at least one tier 1 pattern');
  }
  if (email.length !== 1) {
    throw new PatternError(`patterns.json must declare exactly one email pattern, found ${email.length}`);
  }

  return { tier1, email: email[0], tier2 };
}

// --- rendering --------------------------------------------------------------

const marker = (id) => `[REDACTED:${id}]`;

function replacement(pattern, ref) {
  const { before, after } = pattern.plan;
  return before.map(ref).join('') + marker(pattern.id) + after.map(ref).join('');
}

const goRaw = (value) => `\`${value}\``;
const pyString = (value) => JSON.stringify(value);
const tsString = (value) => JSON.stringify(value);
const csVerbatim = (value) => `@"${value.replaceAll('"', '""')}"`;
const csString = (value) => JSON.stringify(value);

/** Prefixes the inline flag group Go and .NET accept at the start of a pattern. */
const withInlineFlags = (pattern) =>
  pattern.flags.length > 0 ? `(?${pattern.flags.join('')})${pattern.regex}` : pattern.regex;

function renderGo(table, pkg) {
  const goRef = (group) => `\${${group}}`;
  const lines = [
    GO_HEADER,
    '',
    `package ${pkg}`,
    '',
    `import "regexp"`,
    '',
    '// tier1Patterns holds the high-confidence secret formats. Both the full and',
    '// the lightweight redactor apply them. No pattern contains a capturing group:',
    '// tier1Combined maps an alternation group index back to a pattern id.',
    'var tier1Patterns = []secretPattern{',
  ];
  for (const pattern of table.tier1) {
    lines.push(`\t{${JSON.stringify(pattern.id)}, regexp.MustCompile(${goRaw(withInlineFlags(pattern))})},`);
  }
  lines.push(
    '}',
    '',
    "// emailPattern is applied by both redactors, gated by the caller's",
    '// email-redaction option.',
    'var emailPattern = secretPattern{',
    `\tid: ${JSON.stringify(table.email.id)},`,
    `\tre: regexp.MustCompile(${goRaw(withInlineFlags(table.email))}),`,
    '}',
    '',
    '// tier2Patterns holds the heuristic key/value patterns. Only the full',
    '// redactor applies them; each replacement keeps the key and rewrites the value.',
    'var tier2Patterns = []tier2Pattern{',
  );
  for (const pattern of table.tier2) {
    lines.push(
      `\t{`,
      `\t\tid:          ${JSON.stringify(pattern.id)},`,
      `\t\tre:          regexp.MustCompile(${goRaw(withInlineFlags(pattern))}),`,
      `\t\treplacement: ${goRaw(replacement(pattern, goRef))},`,
      `\t},`,
    );
  }
  lines.push('}', '');
  return lines.join('\n');
}

function renderPython(table) {
  const pyRef = (group) => `\\g<${group}>`;
  const flagsExpr = (pattern) => (pattern.flags.includes('i') ? 'BASE_FLAGS | re.IGNORECASE' : 'BASE_FLAGS');
  const lines = [
    `"""Code generated by ${GENERATED_BY} from ${SOURCE_FILE}. DO NOT EDIT."""`,
    '',
    '# ruff: noqa: E501',
    '',
    'import re',
    '',
    '# re.ASCII pins \\b to ASCII word characters. Go RE2 and JavaScript read it that',
    '# way already; without this flag Python reads it as Unicode and leaves a secret',
    '# pressed against a CJK character in clear text.',
    'BASE_FLAGS: int = re.ASCII',
    '',
    '# (id, regex source). No flags and no capturing groups: redaction.py alternates',
    '# these into a single regex, compiled with BASE_FLAGS, and maps the match group',
    '# index back to a pattern id.',
    'TIER1_PATTERNS: tuple[tuple[str, str], ...] = (',
  ];
  for (const pattern of table.tier1) {
    lines.push(`    (${pyString(pattern.id)}, ${pyString(pattern.regex)}),`);
  }
  lines.push(
    ')',
    '',
    '# (id, regex source, flags). Applied by both redactors when the caller enables',
    '# email redaction.',
    'EMAIL_PATTERN: tuple[str, str, int] = (',
    `    ${pyString(table.email.id)},`,
    `    ${pyString(table.email.regex)},`,
    `    ${flagsExpr(table.email)},`,
    ')',
    '',
    '# (id, regex source, flags, replacement template). Applied by the full redactor only.',
    'TIER2_PATTERNS: tuple[tuple[str, str, int, str], ...] = (',
  );
  for (const pattern of table.tier2) {
    lines.push(
      '    (',
      `        ${pyString(pattern.id)},`,
      `        ${pyString(pattern.regex)},`,
      `        ${flagsExpr(pattern)},`,
      `        ${pyString(replacement(pattern, pyRef))},`,
      '    ),',
    );
  }
  lines.push(')', '');
  return lines.join('\n');
}

function renderTypeScript(table) {
  const tsRef = (group) => `$${group}`;
  const flagsLiteral = (pattern, extra) => tsString(`${extra}${pattern.flags.join('')}`);
  const lines = [
    `// Code generated by ${GENERATED_BY} from ${SOURCE_FILE}. DO NOT EDIT.`,
    '',
    '/** One generated secret pattern. `source` and `flags` feed the RegExp constructor. */',
    'export interface GeneratedPattern {',
    '  id: string;',
    '  source: string;',
    '  flags: string;',
    '}',
    '',
    '/** A tier 2 pattern also carries the replacement template that keeps the key. */',
    'export interface GeneratedTier2Pattern extends GeneratedPattern {',
    '  replacement: string;',
    '}',
    '',
    '// High-confidence secret formats, applied by both redaction modes. No pattern',
    '// contains a capturing group: redaction.ts alternates them into a single regex',
    '// and maps the match group index back to a pattern id.',
    'export const tier1Patterns: readonly GeneratedPattern[] = [',
  ];
  for (const pattern of table.tier1) {
    lines.push(
      `  { id: ${tsString(pattern.id)}, source: ${tsString(pattern.regex)}, flags: ${flagsLiteral(pattern, 'g')} },`,
    );
  }
  lines.push(
    '];',
    '',
    '// Applied by both redaction modes when the caller enables email redaction.',
    'export const emailPattern: GeneratedPattern = {',
    `  id: ${tsString(table.email.id)},`,
    `  source: ${tsString(table.email.regex)},`,
    `  flags: ${flagsLiteral(table.email, 'g')},`,
    '};',
    '',
    '// Heuristic key/value patterns, applied by full redaction only.',
    'export const tier2Patterns: readonly GeneratedTier2Pattern[] = [',
  );
  for (const pattern of table.tier2) {
    lines.push(
      '  {',
      `    id: ${tsString(pattern.id)},`,
      `    source: ${tsString(pattern.regex)},`,
      `    flags: ${flagsLiteral(pattern, 'g')},`,
      `    replacement: ${tsString(replacement(pattern, tsRef))},`,
      '  },',
    );
  }
  lines.push('];', '');
  return lines.join('\n');
}

function renderCSharp(table) {
  const csRef = (group) => `\${${group}}`;
  const options = (pattern) => (pattern.flags.includes('i') ? 'BaseOptions | RegexOptions.IgnoreCase' : 'BaseOptions');
  const lines = [
    `// Code generated by ${GENERATED_BY} from ${SOURCE_FILE}. DO NOT EDIT.`,
    '',
    'using System.Text.RegularExpressions;',
    '',
    'namespace Grafana.Agento11y;',
    '',
    '/// <summary>Generated secret-pattern table. Edit redaction/patterns.json instead.</summary>',
    'internal static class RedactionPatterns',
    '{',
    '    /// <summary>',
    '    /// Options for every pattern here and for the tier 1 alternation built in',
    '    /// Redaction.cs. ECMAScript pins <c>\\b</c> to ASCII word characters. Go RE2',
    '    /// and JavaScript read it that way already; without it .NET reads it as',
    '    /// Unicode and leaves a secret pressed against a CJK character in clear text.',
    '    /// CultureInvariant keeps case-insensitive matching off the host culture, so',
    '    /// a Turkish-culture host still matches <c>API_KEY</c>.',
    '    /// </summary>',
    '    internal const RegexOptions BaseOptions =',
    '        RegexOptions.Compiled | RegexOptions.ECMAScript | RegexOptions.CultureInvariant;',
    '',
    '    /// <summary>High-confidence formats, applied by both redaction modes.</summary>',
    '    internal static readonly (string Id, string Source)[] Tier1 =',
    '    [',
  ];
  for (const pattern of table.tier1) {
    lines.push(`        (${csString(pattern.id)}, ${csVerbatim(pattern.regex)}),`);
  }
  lines.push(
    '    ];',
    '',
    '    /// <summary>Applied by both modes when the caller enables email redaction.</summary>',
    '    internal static readonly Regex Email = new(',
    `        ${csVerbatim(table.email.regex)},`,
    `        ${options(table.email)}`,
    '    );',
    '',
    `    internal const string EmailId = ${csString(table.email.id)};`,
    '',
    '    /// <summary>Heuristic key/value patterns, applied by full redaction only.</summary>',
    '    internal static readonly (string Id, Regex Regex, string Replacement)[] Tier2 =',
    '    [',
  );
  for (const pattern of table.tier2) {
    lines.push(
      '        (',
      `            ${csString(pattern.id)},`,
      `            new Regex(${csVerbatim(pattern.regex)}, ${options(pattern)}),`,
      `            ${csString(replacement(pattern, csRef))}`,
      '        ),',
    );
  }
  lines.push('    ];', '}', '');
  return lines.join('\n');
}

/** Renderers, keyed by the repository-relative path each one writes. */
const RENDERERS = {
  'go/agento11y/redaction_patterns_gen.go': (table) => renderGo(table, 'agento11y'),
  'python/agento11y/_redaction_patterns.py': renderPython,
  'js/src/redaction-patterns.generated.ts': renderTypeScript,
  'dotnet/src/Grafana.Agento11y/RedactionPatterns.g.cs': renderCSharp,
  'plugins/agento11y/internal/redact/patterns_gen.go': (table) => renderGo(table, 'redact'),
};

/**
 * Output targets, as repository-relative paths. `check:redaction` reads this
 * list back from the generator's stdout, so a new target is diffed without
 * anyone updating a second copy.
 */
export const targets = Object.keys(RENDERERS);

/** Renders every target. Returns a map of repository-relative path to file body. */
export function render(table) {
  return Object.fromEntries(Object.entries(RENDERERS).map(([target, renderer]) => [target, renderer(table)]));
}

// --- formatting -------------------------------------------------------------

function formatWith(target, command, args, input, options = {}) {
  try {
    return execFileSync(command, args, { input, encoding: 'utf8', ...options });
  } catch (err) {
    const detail = err.stderr ? String(err.stderr).trim() : err.message;
    throw new Error(`${command} failed on ${target}: ${detail}`);
  }
}

/**
 * Runs each language's formatter over the generated body. All three read stdin,
 * so formatting does not depend on where the file is written. The drift job has
 * no .NET SDK, so the C# body is emitted already formatted and `dotnet format`
 * checks it in the .NET job.
 */
export function formatOutputs(files) {
  const formatted = {};
  for (const [target, body] of Object.entries(files)) {
    if (target.endsWith('.go')) {
      formatted[target] = formatWith(target, 'gofmt', [], body);
    } else if (target.endsWith('.py')) {
      formatted[target] = formatWith(target, 'ruff', ['format', '--stdin-filename', target, '-'], body, {
        cwd: repoRoot,
      });
    } else if (target.endsWith('.ts')) {
      formatted[target] = formatWith(
        target,
        'biome',
        ['format', `--stdin-file-path=${path.relative('js', target)}`],
        body,
        { cwd: path.join(repoRoot, 'js') },
      );
    } else {
      formatted[target] = body;
    }
  }
  return formatted;
}

// --- CLI --------------------------------------------------------------------

export function generate({ patternsFile = defaultPatternsFile, outRoot = repoRoot, format = true } = {}) {
  const table = validateTable(JSON.parse(fs.readFileSync(patternsFile, 'utf8')));
  const rendered = render(table);
  const files = format ? formatOutputs(rendered) : rendered;

  for (const [target, body] of Object.entries(files)) {
    const destination = path.join(outRoot, target);
    fs.mkdirSync(path.dirname(destination), { recursive: true });
    fs.writeFileSync(destination, body);
  }
  return Object.keys(files);
}

function main(argv) {
  let patternsFile = defaultPatternsFile;
  let outRoot = repoRoot;
  let format = true;
  let sawOutRoot = false;

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--patterns') {
      patternsFile = path.resolve(argv[++i]);
    } else if (arg === '--no-format') {
      format = false;
    } else if (arg.startsWith('--')) {
      throw new Error(`unknown flag ${arg}`);
    } else if (sawOutRoot) {
      throw new Error('expected at most one output root');
    } else {
      outRoot = path.resolve(arg);
      sawOutRoot = true;
    }
  }

  const written = generate({ patternsFile, outRoot, format });
  for (const target of written) {
    console.log(`generated ${target}`);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    main(process.argv.slice(2));
  } catch (err) {
    console.error(`redaction generator: ${err.message}`);
    process.exit(1);
  }
}
