// Code generated by redaction/scripts/generate.mjs from redaction/patterns.json. DO NOT EDIT.

using System.Text.RegularExpressions;

namespace Grafana.Agento11y;

/// <summary>Generated secret-pattern table. Edit redaction/patterns.json instead.</summary>
internal static class RedactionPatterns
{
    /// <summary>
    /// Options for every pattern here and for the tier 1 alternation built in
    /// Redaction.cs. ECMAScript pins <c>\b</c> to ASCII word characters. Go RE2
    /// and JavaScript read it that way already; without it .NET reads it as
    /// Unicode and leaves a secret pressed against a CJK character in clear text.
    /// CultureInvariant keeps case-insensitive matching off the host culture, so
    /// a Turkish-culture host still matches <c>API_KEY</c>.
    /// </summary>
    internal const RegexOptions BaseOptions =
        RegexOptions.Compiled | RegexOptions.ECMAScript | RegexOptions.CultureInvariant;

    /// <summary>High-confidence formats, applied by both redaction modes.</summary>
    internal static readonly (string Id, string Source)[] Tier1 =
    [
        ("grafana-cloud-token", @"\bglc_[A-Za-z0-9_-]{20,}"),
        ("grafana-service-account-token", @"\bglsa_[A-Za-z0-9_-]{20,}"),
        ("aws-access-token", @"\b(?:A3T[A-Z0-9]|AKIA|ASIA|ABIA|ACCA)[A-Z2-7]{16}\b"),
        ("github-pat", @"\bghp_[A-Za-z0-9_]{36,}"),
        ("github-oauth", @"\bgho_[A-Za-z0-9_]{36,}"),
        ("github-app-token", @"\bghs_[A-Za-z0-9_]{36,}"),
        ("github-fine-grained-pat", @"\bgithub_pat_[A-Za-z0-9_]{82}"),
        ("anthropic-api-key", @"\bsk-ant-api03-[a-zA-Z0-9_-]{93}AA"),
        ("anthropic-admin-key", @"\bsk-ant-admin01-[a-zA-Z0-9_-]{93}AA"),
        ("openai-api-key", @"\bsk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20}"),
        ("openai-project-key", @"\bsk-proj-[a-zA-Z0-9_-]{40,}"),
        ("openai-svcacct-key", @"\bsk-svcacct-[a-zA-Z0-9_-]{40,}"),
        ("gcp-api-key", @"\bAIza[A-Za-z0-9_-]{35}"),
        ("private-key", @"-----BEGIN[A-Z ]*PRIVATE KEY-----[\s\S]*?-----END[A-Z ]*PRIVATE KEY-----"),
        ("connection-string", @"(?:postgres|mysql|mongodb|redis|amqp)://[^ \t\n\f\r\xa0'""]+@[^ \t\n\f\r\xa0'""]+"),
        ("bearer-token", @"[Bb]earer[ \t\n\f\r\xa0]+[A-Za-z0-9_.\-~+/]{20,}={0,3}"),
        ("slack-token", @"\bxox[bporas]-[A-Za-z0-9-]{10,}"),
        ("stripe-key", @"\b[sr]k_(?:live|test)_[A-Za-z0-9]{20,}"),
        ("sendgrid-api-key", @"\bSG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}"),
        ("twilio-api-key", @"\bSK[a-f0-9]{32}"),
        ("npm-token", @"\bnpm_[A-Za-z0-9]{36}"),
        ("pypi-token", @"\bpypi-[A-Za-z0-9_-]{50,}"),
    ];

    /// <summary>Applied by both modes when the caller enables email redaction.</summary>
    internal static readonly Regex Email = new(
        @"\b[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}\b",
        BaseOptions
    );

    internal const string EmailId = "email";

    /// <summary>Heuristic key/value patterns, applied by full redaction only.</summary>
    internal static readonly (string Id, Regex Regex, string Replacement)[] Tier2 =
    [
        (
            "json-secret-field",
            new Regex(@"(""(?:password|secret|token|credential|api_?key|private_?key|access_?key|client_?secret|auth_?token|secret_?key)""[ \t\n\f\r\xa0]*:[ \t\n\f\r\xa0]*"")([^""]+)("")", BaseOptions | RegexOptions.IgnoreCase),
            "${1}[REDACTED:json-secret-field]${3}"
        ),
        (
            "env-secret-quoted-value",
            new Regex(@"(^|[^A-Za-z0-9])((?:PASSWORD|SECRET|TOKEN|KEY|CREDENTIAL|API_KEY|PRIVATE_KEY|ACCESS_KEY)[ \t\n\f\r\xa0]*[=:][ \t\n\f\r\xa0]*"")([^""]+)("")", BaseOptions | RegexOptions.IgnoreCase),
            "${1}${2}[REDACTED:env-secret-quoted-value]${4}"
        ),
        (
            "env-secret-value",
            new Regex(@"(^|[^A-Za-z0-9])((?:PASSWORD|SECRET|TOKEN|KEY|CREDENTIAL|API_KEY|PRIVATE_KEY|ACCESS_KEY)[ \t\n\f\r\xa0]*[=:][ \t\n\f\r\xa0]*)([^ \t\n\f\r\xa0""{}\[\],]+)", BaseOptions | RegexOptions.IgnoreCase),
            "${1}${2}[REDACTED:env-secret-value]"
        ),
    ];
}
