// Code generated by redaction/scripts/generate.mjs from redaction/patterns.json. DO NOT EDIT.

package agento11y

import "regexp"

// tier1Patterns holds the high-confidence secret formats. Both the full and
// the lightweight redactor apply them. No pattern contains a capturing group:
// tier1Combined maps an alternation group index back to a pattern id.
var tier1Patterns = []secretPattern{
	{"grafana-cloud-token", regexp.MustCompile(`\bglc_[A-Za-z0-9_-]{20,}`)},
	{"grafana-service-account-token", regexp.MustCompile(`\bglsa_[A-Za-z0-9_-]{20,}`)},
	{"aws-access-token", regexp.MustCompile(`\b(?:A3T[A-Z0-9]|AKIA|ASIA|ABIA|ACCA)[A-Z2-7]{16}\b`)},
	{"github-pat", regexp.MustCompile(`\bghp_[A-Za-z0-9_]{36,}`)},
	{"github-oauth", regexp.MustCompile(`\bgho_[A-Za-z0-9_]{36,}`)},
	{"github-app-token", regexp.MustCompile(`\bghs_[A-Za-z0-9_]{36,}`)},
	{"github-fine-grained-pat", regexp.MustCompile(`\bgithub_pat_[A-Za-z0-9_]{82}`)},
	{"anthropic-api-key", regexp.MustCompile(`\bsk-ant-api03-[a-zA-Z0-9_-]{93}AA`)},
	{"anthropic-admin-key", regexp.MustCompile(`\bsk-ant-admin01-[a-zA-Z0-9_-]{93}AA`)},
	{"openai-api-key", regexp.MustCompile(`\bsk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20}`)},
	{"openai-project-key", regexp.MustCompile(`\bsk-proj-[a-zA-Z0-9_-]{40,}`)},
	{"openai-svcacct-key", regexp.MustCompile(`\bsk-svcacct-[a-zA-Z0-9_-]{40,}`)},
	{"gcp-api-key", regexp.MustCompile(`\bAIza[A-Za-z0-9_-]{35}`)},
	{"private-key", regexp.MustCompile(`-----BEGIN[A-Z ]*PRIVATE KEY-----[\s\S]*?-----END[A-Z ]*PRIVATE KEY-----`)},
	{"connection-string", regexp.MustCompile(`(?:postgres|mysql|mongodb|redis|amqp)://[^ \t\n\f\r\xa0'"]+@[^ \t\n\f\r\xa0'"]+`)},
	{"bearer-token", regexp.MustCompile(`[Bb]earer[ \t\n\f\r\xa0]+[A-Za-z0-9_.\-~+/]{20,}={0,3}`)},
	{"slack-token", regexp.MustCompile(`\bxox[bporas]-[A-Za-z0-9-]{10,}`)},
	{"stripe-key", regexp.MustCompile(`\b[sr]k_(?:live|test)_[A-Za-z0-9]{20,}`)},
	{"sendgrid-api-key", regexp.MustCompile(`\bSG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}`)},
	{"twilio-api-key", regexp.MustCompile(`\bSK[a-f0-9]{32}`)},
	{"npm-token", regexp.MustCompile(`\bnpm_[A-Za-z0-9]{36}`)},
	{"pypi-token", regexp.MustCompile(`\bpypi-[A-Za-z0-9_-]{50,}`)},
}

// emailPattern is applied by both redactors, gated by the caller's
// email-redaction option.
var emailPattern = secretPattern{
	id: "email",
	re: regexp.MustCompile(`\b[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}\b`),
}

// tier2Patterns holds the heuristic key/value patterns. Only the full
// redactor applies them; each replacement keeps the key and rewrites the value.
var tier2Patterns = []tier2Pattern{
	{
		id:          "json-secret-field",
		re:          regexp.MustCompile(`(?i)("(?:password|secret|token|credential|api_?key|private_?key|access_?key|client_?secret|auth_?token|secret_?key)"[ \t\n\f\r\xa0]*:[ \t\n\f\r\xa0]*")([^"]+)(")`),
		replacement: `${1}[REDACTED:json-secret-field]${3}`,
	},
	{
		id:          "env-secret-quoted-value",
		re:          regexp.MustCompile(`(?i)(^|[^A-Za-z0-9])((?:PASSWORD|SECRET|TOKEN|KEY|CREDENTIAL|API_KEY|PRIVATE_KEY|ACCESS_KEY)[ \t\n\f\r\xa0]*[=:][ \t\n\f\r\xa0]*")([^"]+)(")`),
		replacement: `${1}${2}[REDACTED:env-secret-quoted-value]${4}`,
	},
	{
		id:          "env-secret-value",
		re:          regexp.MustCompile(`(?i)(^|[^A-Za-z0-9])((?:PASSWORD|SECRET|TOKEN|KEY|CREDENTIAL|API_KEY|PRIVATE_KEY|ACCESS_KEY)[ \t\n\f\r\xa0]*[=:][ \t\n\f\r\xa0]*)([^ \t\n\f\r\xa0"{}\[\],]+)`),
		replacement: `${1}${2}[REDACTED:env-secret-value]`,
	},
}
