"""Code generated by redaction/scripts/generate.mjs from redaction/patterns.json. DO NOT EDIT."""

# ruff: noqa: E501

import re

# re.ASCII pins \b to ASCII word characters. Go RE2 and JavaScript read it that
# way already; without this flag Python reads it as Unicode and leaves a secret
# pressed against a CJK character in clear text.
BASE_FLAGS: int = re.ASCII

# (id, regex source). No flags and no capturing groups: redaction.py alternates
# these into a single regex, compiled with BASE_FLAGS, and maps the match group
# index back to a pattern id.
TIER1_PATTERNS: tuple[tuple[str, str], ...] = (
    ("grafana-cloud-token", "\\bglc_[A-Za-z0-9_-]{20,}"),
    ("grafana-service-account-token", "\\bglsa_[A-Za-z0-9_-]{20,}"),
    ("aws-access-token", "\\b(?:A3T[A-Z0-9]|AKIA|ASIA|ABIA|ACCA)[A-Z2-7]{16}\\b"),
    ("github-pat", "\\bghp_[A-Za-z0-9_]{36,}"),
    ("github-oauth", "\\bgho_[A-Za-z0-9_]{36,}"),
    ("github-app-token", "\\bghs_[A-Za-z0-9_]{36,}"),
    ("github-fine-grained-pat", "\\bgithub_pat_[A-Za-z0-9_]{82}"),
    ("anthropic-api-key", "\\bsk-ant-api03-[a-zA-Z0-9_-]{93}AA"),
    ("anthropic-admin-key", "\\bsk-ant-admin01-[a-zA-Z0-9_-]{93}AA"),
    ("openai-api-key", "\\bsk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20}"),
    ("openai-project-key", "\\bsk-proj-[a-zA-Z0-9_-]{40,}"),
    ("openai-svcacct-key", "\\bsk-svcacct-[a-zA-Z0-9_-]{40,}"),
    ("gcp-api-key", "\\bAIza[A-Za-z0-9_-]{35}"),
    ("private-key", "-----BEGIN[A-Z ]*PRIVATE KEY-----[\\s\\S]*?-----END[A-Z ]*PRIVATE KEY-----"),
    (
        "connection-string",
        "(?:postgres|mysql|mongodb|redis|amqp)://[^ \\t\\n\\f\\r\\xa0'\"]+@[^ \\t\\n\\f\\r\\xa0'\"]+",
    ),
    ("bearer-token", "[Bb]earer[ \\t\\n\\f\\r\\xa0]+[A-Za-z0-9_.\\-~+/]{20,}={0,3}"),
    ("slack-token", "\\bxox[bporas]-[A-Za-z0-9-]{10,}"),
    ("stripe-key", "\\b[sr]k_(?:live|test)_[A-Za-z0-9]{20,}"),
    ("sendgrid-api-key", "\\bSG\\.[A-Za-z0-9_-]{22}\\.[A-Za-z0-9_-]{43}"),
    ("twilio-api-key", "\\bSK[a-f0-9]{32}"),
    ("npm-token", "\\bnpm_[A-Za-z0-9]{36}"),
    ("pypi-token", "\\bpypi-[A-Za-z0-9_-]{50,}"),
)

# (id, regex source, flags). Applied by both redactors when the caller enables
# email redaction.
EMAIL_PATTERN: tuple[str, str, int] = (
    "email",
    "\\b[A-Za-z0-9._%+\\-]+@[A-Za-z0-9.\\-]+\\.[A-Za-z]{2,}\\b",
    BASE_FLAGS,
)

# (id, regex source, flags, replacement template). Applied by the full redactor only.
TIER2_PATTERNS: tuple[tuple[str, str, int, str], ...] = (
    (
        "json-secret-field",
        '("(?:password|secret|token|credential|api_?key|private_?key|access_?key|client_?secret|auth_?token|secret_?key)"[ \\t\\n\\f\\r\\xa0]*:[ \\t\\n\\f\\r\\xa0]*")([^"]+)(")',
        BASE_FLAGS | re.IGNORECASE,
        "\\g<1>[REDACTED:json-secret-field]\\g<3>",
    ),
    (
        "env-secret-quoted-value",
        '(^|[^A-Za-z0-9])((?:PASSWORD|SECRET|TOKEN|KEY|CREDENTIAL|API_KEY|PRIVATE_KEY|ACCESS_KEY)[ \\t\\n\\f\\r\\xa0]*[=:][ \\t\\n\\f\\r\\xa0]*")([^"]+)(")',
        BASE_FLAGS | re.IGNORECASE,
        "\\g<1>\\g<2>[REDACTED:env-secret-quoted-value]\\g<4>",
    ),
    (
        "env-secret-value",
        '(^|[^A-Za-z0-9])((?:PASSWORD|SECRET|TOKEN|KEY|CREDENTIAL|API_KEY|PRIVATE_KEY|ACCESS_KEY)[ \\t\\n\\f\\r\\xa0]*[=:][ \\t\\n\\f\\r\\xa0]*)([^ \\t\\n\\f\\r\\xa0"{}\\[\\],]+)',
        BASE_FLAGS | re.IGNORECASE,
        "\\g<1>\\g<2>[REDACTED:env-secret-value]",
    ),
)
